included:
  - Sources
  - Tests

# Standard rules for Sources directory
function_body_length:
  warning: 100
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

type_name:
  min_length: 3
  max_length: 40

# Exclude generated or dependency files
excluded:
  - .build
  - Carthage
  - Pods
  - .swiftpm
  - .git
  - .github

# Override rules specifically for test files
# Use child config approach for test-specific rules
child_config: .swiftlint-tests.yml