# Relaxed rules specifically for test files
function_body_length:
  warning: 150
  error: 200

type_body_length:
  warning: 500
  error: 600

file_length:
  warning: 800
  error: 1500

type_name:
  min_length: 3
  max_length: 60