# Codecov configuration to exclude test files
ignore:
  - "src/test/**/*"
  - "**/test/**/*"

# Coverage settings
coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%

# Comment settings
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
