name: Swift Lint & Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["**"]

jobs:
  build:
    name: Build & Test (${{ matrix.os }} / Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04]
        swift: ["5.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Install SwiftLint
        if: matrix.os == 'macos-latest'
        run: |
          brew install swiftlint

      - name: Lint (SwiftLint)
        if: matrix.os == 'macos-latest'
        run: swiftlint
        continue-on-error: true

      - name: Build
        run: swift build --build-tests

      - name: Run Tests
        run: swift test --enable-test-discovery
