name: Swift Lint & Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["**"]

permissions:
  contents: write

jobs:
  build:
    name: Build & Test (${{ matrix.os }} / Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}

      - name: Install SwiftLint
        if: matrix.os == 'macos-latest'
        run: |
          brew install swiftlint

      - name: Lint (SwiftLint)
        if: matrix.os == 'macos-latest'
        run: swiftlint

      - name: Build
        run: swift build --build-tests -Xswiftc -warnings-as-errors

      - name: Run Tests
        run: swift test --enable-test-discovery -Xswiftc -warnings-as-errors

  update-badge:
    name: Update Vibe Coded Badge
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip vibe-badge]')"
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: trieloff/vibe-coded-badge-action@main
